### ISSUE TITLE
Cannot create_task

### ISSUE THREAD

**Issue by aqua-hopps** [aqua-hopps/matcha-bot#1]
```
Error while executing Future callback.
Traceback (most recent call last):
  File "/home/ubuntu/matcha-bot/venv/lib/python3.11/site-packages/google/api_core/future/_helpers.py", line 37, in safe_invoke_callback
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/matcha-bot/newnew.py", line 208, in get_external_ip
    asyncio.create_task(send_details(ip))
  File "/usr/lib/python3.11/asyncio/tasks.py", line 371, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
/home/ubuntu/matcha-bot/venv/lib/python3.11/site-packages/google/api_core/future/_helpers.py:39: RuntimeWarning: coroutine 'book_command.<locals>.send_details' was never awaited
  _LOGGER.exception("Error while executing Future callback.")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

`asyncio.create_task(send_details(ip))`
`asyncio.create_task(release_instance())`

Fails randomly.

**Comment by aqua-hopps** [comment]
12088bb58a20b875e984ffa0b8d352987a403af6 - Simply run the functions in synchronously.
